version = 1

test_patterns = [
  "tests/**"
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

  [analyzers.meta]
  skip_doc_coverage = ["class", "magic", "nonpublic"]

